// Package docs Code generated by hand for complaint service
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@messenger.local"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/complaints": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Пользователь видит только свои жалобы, администратор — все",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaints"
                ],
                "summary": "Получить список жалоб",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу (pending/in_progress/resolved/rejected)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтр по автору (только для администратора)",
                        "name": "author_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит результатов (по умолчанию 50, максимум 100)",
                        "name": "limit",
                        "in": "query",
                        "default": 50
                    },
                    {
                        "type": "integer",
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query",
                        "default": 0
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplaintListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новую жалобу от текущего пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaints"
                ],
                "summary": "Создать жалобу",
                "parameters": [
                    {
                        "description": "Данные жалобы",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateComplaintRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ComplaintResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/complaints/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Детальная информация по жалобе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaints"
                ],
                "summary": "Получить жалобу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID жалобы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplaintDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Физически удаляет жалобу и историю",
                "tags": [
                    "complaints"
                ],
                "summary": "Удалить жалобу (админ)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID жалобы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/complaints/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет статус жалобы и добавляет запись в историю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "complaints"
                ],
                "summary": "Изменить статус жалобы (админ)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID жалобы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ComplaintStatusHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ComplaintDetailResponse": {
            "type": "object",
            "properties": {
                "assigned_to": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "author": {
                    "type": "integer",
                    "example": 1
                },
                "author_login": {
                    "type": "string",
                    "example": "ivan@example.com"
                },
                "author_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "device_description": {
                    "type": "string",
                    "example": "Windows 10, Chrome 120.0, 16GB RAM"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "status_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ComplaintStatusHistoryResponse"
                    }
                },
                "text": {
                    "type": "string",
                    "example": "Application crashes when uploading large files"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.ComplaintListResponse": {
            "type": "object",
            "properties": {
                "complaints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ComplaintResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.ComplaintResponse": {
            "type": "object",
            "properties": {
                "assigned_to": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "author": {
                    "type": "integer",
                    "example": 1
                },
                "author_login": {
                    "type": "string",
                    "example": "ivan@example.com"
                },
                "author_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "device_description": {
                    "type": "string",
                    "example": "Windows 10, Chrome 120.0, 16GB RAM"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "text": {
                    "type": "string",
                    "example": "Application crashes when uploading large files"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        },
        "models.ComplaintStatusHistoryResponse": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string",
                    "example": "2024-01-01T14:00:00Z"
                },
                "changed_by": {
                    "type": "integer",
                    "example": 1
                },
                "changed_by_login": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "comment": {
                    "type": "string",
                    "example": "Investigating the issue"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "type": "string",
                    "example": "in_progress"
                }
            }
        },
        "models.CreateComplaintRequest": {
            "type": "object",
            "required": [
                "device_description",
                "text"
            ],
            "properties": {
                "device_description": {
                    "type": "string",
                    "example": "Windows 10, Chrome 120.0, 16GB RAM"
                },
                "text": {
                    "type": "string",
                    "example": "Application crashes when uploading large files"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "not found"
                }
            }
        },
        "models.UpdateStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "Issue fixed in version 1.2.3"
                },
                "status": {
                    "type": "string",
                    "example": "resolved"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT токен в формате: Bearer {token}. Gateway проверяет токен и добавляет X-User-ID в заголовок",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8086",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Complaint Service API",
	Description:      "Микросервис обработки жалоб пользователей для корпоративного мессенджера",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
